packages:
  - "projects/*"
  - "projects/*/services/*"
  - "projects/*/apps/*/src/app/pages"
  - "projects/*/apps/*/src/app/cards"
  - "projects/*/apps/*/src/app/settings"
  - "packages/*"

allowBuilds:
  esbuild: true
