{
  "uid": "__SPOTKIT_UID___example_agent_tool",
  "type": "workflow-action",
  "config": {
    "actionUrl": "__SPOTKIT_API_ORIGIN_JSON__/workflow-actions/agent-tool",
    "isPublished": false,
    "supportedClients": [
      { "client": "WORKFLOWS" },
      { "client": "AGENTS" }
    ],
    "inputFields": [
      {
        "typeDefinition": {
          "name": "instruction",
          "type": "string",
          "fieldType": "textarea"
        },
        "supportedValueTypes": ["STATIC_VALUE"],
        "isRequired": true
      }
    ],
    "outputFields": [
      {
        "typeDefinition": {
          "name": "result",
          "type": "string",
          "fieldType": "text"
        }
      }
    ],
    "labels": {
      "en": {
        "actionName": "__SPOTKIT_DISPLAY_NAME_JSON__: example agent tool",
        "actionDescription": "Runs a secure external tool generated by SpotKit.",
        "actionCardContent": "Run the external agent tool",
        "inputFieldLabels": { "instruction": "Instruction" },
        "inputFieldDescriptions": {
          "instruction": "Describe the operation the tool should perform."
        },
        "outputFieldLabels": { "result": "Tool result" }
      }
    },
    "objectTypes": ["CONTACT"]
  }
}
