{
  "uid": "__SPOTKIT_UID___example_workflow_action",
  "type": "workflow-action",
  "config": {
    "actionUrl": "__SPOTKIT_API_ORIGIN_JSON__/workflow-actions/example",
    "isPublished": false,
    "supportedClients": [{ "client": "WORKFLOWS" }],
    "inputFields": [
      {
        "typeDefinition": {
          "name": "message",
          "type": "string",
          "fieldType": "textarea"
        },
        "supportedValueTypes": ["STATIC_VALUE"],
        "isRequired": true
      },
      {
        "typeDefinition": {
          "name": "priority",
          "type": "enumeration",
          "fieldType": "select",
          "options": [
            { "value": "high", "label": "High priority" },
            { "value": "normal", "label": "Normal priority" },
            { "value": "low", "label": "Low priority" }
          ]
        },
        "supportedValueTypes": ["STATIC_VALUE"],
        "isRequired": true
      }
    ],
    "outputFields": [
      {
        "typeDefinition": {
          "name": "status",
          "type": "string",
          "fieldType": "text"
        }
      }
    ],
    "labels": {
      "en": {
        "actionName": "__SPOTKIT_DISPLAY_NAME_JSON__: example action",
        "actionDescription": "Runs a secure external action generated by SpotKit.",
        "actionCardContent": "Send a {{priority}} priority message",
        "inputFieldLabels": {
          "message": "Message",
          "priority": "Priority"
        },
        "inputFieldDescriptions": {
          "message": "Enter the message for the external action.",
          "priority": "Choose how urgently the action should run."
        },
        "outputFieldLabels": { "status": "Execution status" }
      }
    },
    "objectTypes": ["CONTACT"]
  }
}
