HUBSPOT_CLIENT_ID=
HUBSPOT_CLIENT_SECRET=
HUBSPOT_SCOPES=oauth crm.objects.deals.read
PUBLIC_URL=__SPOTKIT_API_ORIGIN__
TOKEN_ENCRYPTION_KEY=replace-with-a-long-random-secret
UPSTASH_REDIS_REST_URL=
UPSTASH_REDIS_REST_TOKEN=
ALLOW_UNSIGNED_DEVELOPMENT_REQUESTS=false
# Volatile stores for a temporary HTTPS tunnel; signature checks stay enabled.
ALLOW_EPHEMERAL_TUNNEL_DEVELOPMENT=false
PORT=8788
